### ISSUE TITLE
More packages needed to build WSL2 linux kernel

### ISSUE THREAD

**Issue by timsu92** [dorssel/usbipd-win#870] opened 2024-02-17 12:32 UTC
In the wiki, there's [a section telling us how to build our own kernel](https://github.com/dorssel/usbipd-win/wiki/WSL-support#building-your-own-wsl-2-kernel-with-additional-drivers). However, the packages listed aren't enough. In Ubuntu-22.04 in WSL2, `bc` and `dwarves` are required to be installed as well. Both of them can be installed using apt.

**Comment by dorssel** [comment] 2024-02-18 00:05
The documentation already says:

> Depending on the drivers you will select below, additional packages may be required.

Duplicate of https://github.com/dorssel/usbipd-win/issues/731

**Closed by dorssel** 2024-02-18 00:05 UTC
