### ISSUE TITLE
Only usbipd is provided by the installer

### ISSUE THREAD

**Issue by fakuivan** [dorssel/usbipd-win#171] opened 2021-12-23 13:00 UTC
While this works fine for Windows host and a Linux client, using a Windows client is not possible. Are there any plans on adding the client for windows too? Are there any workarounds for this at the time being?

**Comment by dorssel** [comment] 2021-12-23 14:59
Duplicate of #65
It appears a USBIP client for Windows exists in another project, see #79

**Closed** 2021-12-23 20:53 UTC
