### ISSUE TITLE
How to get access usb ext device

### ISSUE THREAD

**Issue by oim37** [dorssel/usbipd-win#737] opened 2023-10-22 11:37 UTC
Hello,

I attach my usb device it  ext file system external usb disk 3TB Seagate

```powershell
usbipd wsl list
BUSID  VID:PID    DEVICE                                                        STATE
5-2    0bc2:a0a1  USB storage device                               Attached - WSL
```
dmesg
```bash
[ 2175.208933] vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(3)
[ 2175.209818] vhci_hcd vhci_hcd.0: devid(327682) speed(3) speed_str(high-speed)
[ 2175.210757] vhci_hcd vhci_hcd.0: Device attached
[ 2175.551720] usb 1-1: new high-speed USB device number 3 using vhci_hcd
[ 2175.701723] usb 1-1: SetAddress Request (3) to port 0
[ 2175.811582] usb 1-1: New USB device found, idVendor=0bc2, idProduct=a0a1, bcdDevice= 1.00
[ 2175.818411] usb 1-1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[ 2175.820008] usb 1-1: Product: Backup+ Desk
[ 2175.820806] usb 1-1: Manufacturer: Seagate
[ 2175.821600] usb 1-1: SerialNumber: NA5J2TB5
```
fdisk -l and df -h not show new device, how to get access to files on disk?

**Comment by dorssel** [comment] 2023-10-22 15:25
Duplicate of https://github.com/dorssel/usbipd-win/issues/345

**Closed by dorssel** 2023-10-22 15:25 UTC
