### ISSUE TITLE
Can not find the USB storage device after attaching it.

### ISSUE THREAD

**Issue by qwwong** [dorssel/usbipd-win#864] opened 2024-02-12 16:10 UTC
I attached a USB storage to WSL ( Ubuntu 22.04). I can find the device using "lsusb". But there is no new device under /dev folder. Please refer the screen shot which includes the status before and after attching the USB device.
![screenshot 000451](https://github.com/dorssel/usbipd-win/assets/64942384/4f986997-d88a-4b1a-a714-7b4700e325c8)

**Comment by proddy** [comment] 2024-02-12 17:49
I have a similar problem (using 4.1.1). Some USB devices appear in /dev/ttyUSB* while others don't, although they disappear from Windows' Device Manager and no errors are shown during binding.

**Comment by dorssel** [comment] 2024-02-12 21:02
Duplicate of https://github.com/dorssel/usbipd-win/issues/735

**Closed by dorssel** 2024-02-12 21:02 UTC
