### ISSUE TITLE
updated to the latest wsl2 and have issues with usbipd

### ISSUE THREAD

**Issue by ulao** [dorssel/usbipd-win#749] opened 2023-11-05 14:00 UTC
C:\Windows\System32>usbipd wsl attach --busid 2-3
usbipd: info: Using default WSL distribution 'Ubuntu'; specify the '--distribution' option to select a different one.
usbipd: error: The selected WSL distribution cannot be reached via the WSL virtual switch; try restarting the WSL distribution.

I tried some recommendation found here  https://github.com/dorssel/usbipd-win/wiki/WSL-support
but they are not fixing the issue.
 
FYI: I'm running in mirrored mode.
 wslinfo --networking-mode
mirrored

Where can I go from here to make this work?

Ubuntu (Default)
Ubuntu-22.04

**Comment by dorssel** [comment] 2023-11-05 21:13
Duplicate of https://github.com/dorssel/usbipd-win/issues/714

**Closed** 2023-11-05 21:15 UTC
