### ISSUE TITLE
 super-speed-plus (ASUS ROG STRIX Arion) fails to attach

### ISSUE THREAD

**Issue by Fredolx** [dorssel/usbipd-win#259] opened 2022-02-12 05:17 UTC
Kernel: 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu WSL 2
USBIPD 2.1.0
Windows 11

When trying to attach my ASUS ROG STRIX Arion with ```usbipd wsl attach``` (it gets detected as ```USB Attached SCSI (UAS) Mass Storage Device``` with ```wsl --list --verbose```), I get these error messages:

```
usbip: error: import device
usbipd: error: Failed to attach device with BUSID '1-22'.
```
After running ```dmesg | tail```:
```
vhci_hcd: Failed attach request for unsupported USB speed: super-speed-plus
```

Thank you

**Comment by dorssel** [comment] 2022-02-12 10:13
@Fredolx 
Duplicate of #137 

I investigated a bit. It turns out that the Linux kernel (not just WSL, but *all* Linux kernels) does not support USB 3.1 Gen2 (super-speed-plus) over USBIP. `usbipd-win` does, so it reports super-speed-plus, but then Linux cannot handle it.

See Linux source code:
https://elixir.bootlin.com/linux/v5.10.60/source/drivers/usb/usbip/vhci_sysfs.c#L288

To resolve, you could connect this device to a different (non 3.1 Gen2) port, maybe you have a 3.0 or even 2.0 port available? Alternatively, you could connect a 3.0 or 2.0 hub between the port and the device.

Would you be willing to test a version that simply lies about the speed? I mean `usbipd-win` reporting super-speed instead of super-speed-plus. I have no idea if that could even work. I know for a fact that lying about USB1/USB2/USB3 does *not* work, but maybe lying about 3.0/3.1/3.1Gen2 works...

**Comment by dorssel** [comment] 2022-02-12 11:01
@Fredolx 
I've created PR #260 that may fix the problem. The installer is at https://github.com/dorssel/usbipd-win/actions/runs/1833543256.
Could you test that?

**Comment by dorssel** [comment] 2022-03-12 15:16
Closing due to lack of response.

**Closed by dorssel** 2022-03-12 15:16 UTC
Labels: USBIP
