### ISSUE TITLE
Attaching a device to a Arch Linux WSL2 failed

### ISSUE THREAD

**Issue by Rottenbeer** [dorssel/usbipd-win#909] opened 2024-03-30 12:13 UTC
Hi!

I can't attach a device to my Arch Linux WSL2, but it works for Ubuntu:

PS C:\Users\rotte> usbipd attach --wsl "Ubuntu-22.04" -i 10c4:ea60 -a
usbipd: info: Device with hardware-id '10c4:ea60' found at busid '1-7'.
usbipd: info: Selecting a specific distribution is no longer required. Please file an issue if you believe that the default selection mechanism is not working for you.
usbipd: info: Using WSL distribution 'Ubuntu-22.04' to attach; the device will be available in all WSL 2 distributions.
usbipd: info: Using IP address 172.24.64.1 to reach the host.
usbipd: info: Starting endless attach loop; press Ctrl+C to quit.
WSL Attached 
C:\Users\rotte> usbipd attach --wsl Arch -i 10c4:ea60 -a
usbipd: info: Device with hardware-id '10c4:ea60' found at busid '1-7'.
usbipd: info: Selecting a specific distribution is no longer required. Please file an issue if you believe that the default selection mechanism is not working for you.
usbipd: info: Using WSL distribution 'Arch' to attach; the device will be available in all WSL 2 distributions. 
usbipd: error: Mounting 'C:\Program Files\usbipd-win\WSL' within WSL failed.

PS C:\Users\rotte> wsl --list --verbose
NAME            STATE           VERSION
*Ubuntu-22.04    Running         2 
Arch            Stopped         2 

PS C:\Users\rotte> usbipd attach --help                                                                                                                                                          usbipd-win 4.1.0 

Even though you say, that it's not necessary to specify a Linux Distribution, I'd soon like to remove the Ubuntu WSL and  fear I can't attach the usb device afterwards?

**Comment by dorssel** [comment] 2024-03-30 12:35
Duplicate of https://github.com/dorssel/usbipd-win/issues/856

It's been fixed in the master branch. You can find the installer here https://github.com/dorssel/usbipd-win/actions/runs/8413402184

**Closed by dorssel** 2024-03-30 12:35 UTC
