### ISSUE TITLE
Feature request: automatically device attaching to wsl

### ISSUE THREAD

**Issue by epiciskandar** [dorssel/usbipd-win#217] opened 2022-01-20 08:25 UTC
This software definitly give a great helping on device developing, like Android application development. but since unpluging and repluging is so frequently actions, each time I have to reattach device in the Windows Powershell console, so could we have an automatically attaching options, like #56, but just for different scenario.

**Comment by dorssel** [comment] 2022-01-20 23:21
@epiciskandar 
Thanks for the suggestion. This is still an exact duplicate of #56, so closing.

See https://github.com/dorssel/usbipd-win/discussions/168#discussioncomment-1841785 for a hint on how you can accomplish this already from the Linux side with a little bit of scripting.

**Closed by dorssel** 2022-01-20 23:21 UTC
