### ISSUE TITLE
Need help: BSOD when using wsl attach

### ISSUE THREAD

**Issue by loeffelpan** [dorssel/usbipd-win#200] opened 2022-01-14 14:50 UTC
Hey, I'm using _WSL Ubuntu 20.04 on Win10 21H2_ with _usbipd-win-1.2.0_ and would like to attach my ledger nano to sideload an app.
Unfortunately I got an BSOD with following stopcode when using the _wsl attach_-command.

PNP_DETECTED_FATAL_ERROR

Can you please help me figuring out whats wrong?

**Comment by dorssel** [comment] 2022-01-14 15:05
@loeffelpan 
Woah, BSOD ... that's not good! You're the first to report such a serious issue.

Did the bluescreen report the kernel module/driver that caused the crash? It could be the VBox drivers, but also the hub driver. What type of hub is your device connected to? Can you try using a different port/hub/computer? First we need to find out if it is machine, hub, hub-driver, or device related.

What version of `usbipd-win` are you using? 1.3.0? Could you try the latest master build? You can find it here: https://github.com/dorssel/usbipd-win/actions/runs/1695796183.

**Comment by loeffelpan** [comment] 2022-01-14 16:58
After some testing with different devices and different ports/hub I would guess that issue is hub- or hub-driver related. Any device with another hub number is working fine. Any device connected with bus id 4-x leads to BSOD. Other bus id (e. g. 5-x) seem to work.
I just attached the ledger with bus id 5-2 and just **connected** an device to bus id 4-2 and got an blue screen. Maybe this isn't really related to your project.

If you want, you can close this issue. But I'm also ready for further investigation if it would be helpful for you. Your descision.

**Comment by dorssel** [comment] 2022-01-14 23:02
@loeffelpan 
When `usbipd-win` 1.2.0 attaches a device, effectively an unplug/replug is simulated (USB port reset). That explains why you are experiencing this during `wsl attach`. This strategy has changed for 1.3.0 (which does a disable/enable cycle instead) and again in the current master (which does a pause/restart cycle instead). So, you may have better luck with one of those.

However, I think we can indeed conclude that the problem is with the hub; not something that `usbipd-win` can fix. So, I will close this ticket. But I am interested to find out what the root cause is anyway. Can you locate the root port and the hub(s) in the Window Device Manager? (best select: view->by connection). Are the hubs using the standard Microsoft drivers? What happens if you "Update driver" on the hub or the root port? Finally, it could be some third-party USB filter driver. What is the output of:

```
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}" /v UpperFilters
```

**Closed by dorssel** 2022-01-14 23:02 UTC

**Comment by loeffelpan** [comment] 2022-01-16 10:10
> So, you may have better luck with one of those.
Unfortunately I got #152 with 1.3.0. Didn't try master branch. Maybe this would work.
 
> Can you locate the root port and the hub(s) in the Window Device Manager? (best select: view->by connection). Are the hubs using the standard Microsoft drivers? What happens if you "Update driver" on the hub or the root port?
I'm not sure if this is the right device. _Update driver_ says that driver is up to date and it is using standard drivers as you can see here.
![image](https://user-images.githubusercontent.com/34661317/149655610-7055e10b-567b-4d66-991a-867a84c3809b.png)

> Finally, it could be some third-party USB filter driver. What is the output of:
> 
> ```
> reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}" /v UpperFilters
> ```
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}
    UpperFilters    REG_MULTI_SZ    EUsbHubFilter
```

**Comment by dorssel** [comment] 2022-01-16 10:16
@loeffelpan 
There is your problem:

> UpperFilters    REG_MULTI_SZ    EUsbHubFilter

Seems to be part of "flexihub". Google "flexihub" + "BSOD". You may want to uninstall that.

**Comment by loeffelpan** [comment] 2022-01-16 10:25
Wow... thanks for that (lightning fast) reply and advice. Youre right. I've used Flexihub some time ago. I will uninstall it as I don't need it for now.

Thanks
