### ISSUE TITLE
无法映射安卓9008端口

### ISSUE THREAD

**Issue by yuxuxin233** [dorssel/usbipd-win#609] opened 2023-05-27 14:05 UTC
![2](https://github.com/dorssel/usbipd-win/assets/73999603/5eab6da8-7533-4073-bb79-cc5214f2e9de)
![3](https://github.com/dorssel/usbipd-win/assets/73999603/825454b8-689a-42ff-977e-a72055f3d6e8)
![4](https://github.com/dorssel/usbipd-win/assets/73999603/4717709b-db61-4d4f-98f3-19e725432d8e)
![1](https://github.com/dorssel/usbipd-win/assets/73999603/74aa276d-bebb-481a-ae5d-4d418ea6f59e)

**Comment by dorssel** [comment] 2023-05-27 14:51
Like the warning says: you have an incompatible USB filter driver installed. Either remove it (it is part of https://github.com/daynix/UsbDk), or else first issue `usbipd bind --busid 2-2 --force`.

Duplicate of #264

**Comment by yuxuxin233** [comment] 2023-05-27 14:58
> 

![5](https://github.com/dorssel/usbipd-win/assets/73999603/156c8bee-a38d-4cff-8fa9-b4239b5b31ed)
谢谢

**Closed** 2023-05-28 00:42 UTC

**Comment by TaylorTWBrown** [comment] 2023-05-30 01:38
Can you provide any context to this issue? I seem to have the same error. Recently upgraded to 3.0.0

**Comment by yuxuxin233** [comment] 2023-05-30 03:19
> 你能提供这个问题的任何背景吗？我似乎有同样的错误。最近升级到 3.0.0

抱歉。我问题复现。没有找到有效方法
